name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory:  "terraform"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Initialize Terraform
        run: terraform init

      - name: Planning Terraform
        run: terraform plan

      - name: Deploy Infrastructure
        run: terraform apply -auto-approve

      - name: Save Terraform State
        run: terraform state pull > terraform.tfstate

      - name: Upload Terraform State
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: terraform.tfstate
